### ISSUE TITLE
Is iD fully working?

### ISSUE THREAD

**Issue by syncush** [MapColonies/osm-depolyment-stack#15]
Can we create multiple users?
Can regular users create changesets and admins can approve them?
Are we are able to register users and manage admins and editors correctly?

**Comment by galta95** [comment]
1. Yes we can, and we dont need to configure id to every user (one time is enough).
2. Can regular users create changesets?  - Yes, admins can approve them? -  every user can edit without approve.
3. We can manage the users but it does not affect on thier permissions on the website
